language: go
go:
  - 1.x

sudo: required
services:
  - docker

env:
  - GOVERSION=1.9
  - GOVERSION=1.10

install: true

script:
  - ./run_tests.sh $GOVERSION

notifications:
  slack:
    rooms:
      secure: OcOp0eh2Xyz22v/zMhKNzL5Ng6X01Jy0rtgiq5hDfO0ur8Tl4l6/dl23vrr4nMH/FY+55ZX/F679do45L3BBpETBYfdCGZA/VPvFFzQdSm8onrrm3YT486yKA7PzWVy3JUPgywz+Rm49e0Vb9qbzrkekbpKnBHKbkY1JwwWvhBfcNoFv4u0wJuPooJVM7J4oUxneqWzU8cdoMDQ8dOc9PkxszCs0kF5GMMzgIdTzOchz3gK74icGx91H5y6nzB0UVzuQTTnKFVIBc/A/DOr2USt/PBVHqAXMFAymqt+eds1N21MJA/VCm8PEjVDznUu6HS8rUc9ACnLoz2tjG/4ccFjkufnQGJde6zFLzn6q2fEF3VT1x20wtnlGyQ6jo2E7ZNLSUvX9RTltOxpTIXh4bwYeb5GeJfnQmhlqI3Jcym7LB4A6xdWKIiEvykoHN23cMrDk8trfB62vJQLbk9XZMKF8bEogoRR11xuoRbukFXMiaIAlnsQrwoMgILUsZZT8vl2PZ4SG7wK0iPJ9sQJWcRPgBgMTIDQbik33Kd4N0Dmf5gz8oP2cmFYCYiS/vmy9yuO0rX6Z87FH0YqRHLCmG9NBpTUEpdJWNaUC1+VgIS9pS7fldNhFfwiZ92QGzKUAJUogavpdXMQNJU5TTxXuh04rFeAbZQVsNzhT2uz2ATI=
